# MPLAB IDE generated this makefile for use with GNU make.
# Project: OR_SYSTEM_FIRMWARE.mcp
# Date: Thu Nov 20 14:25:54 2014

AS = MPASMWIN.exe
CC = mcc18.exe
LD = mplink.exe
AR = mplib.exe
RM = rm

output/OR_SYSTEM_FIRMWARE.cof : obj/Announce.o obj/ARP.o obj/AutoIP.o obj/BerkeleyAPI.o obj/Delay.o obj/DHCP.o obj/DHCPs.o obj/DNS.o obj/DNSs.o obj/DynDNS.o obj/ETH97J60.o obj/FTP.o obj/Hashes.o obj/Helpers.o obj/HTTP2.o obj/ICMP.o obj/IP.o obj/LCDBlocking.o obj/MPFS2.o obj/NBNS.o obj/SMTP.o obj/SNMP.o obj/SNMPv3.o obj/SNMPv3USM.o obj/SNTP.o obj/SPIEEPROM.o obj/SPIFlash.o obj/SPIRAM.o obj/SSL.o obj/StackTsk.o obj/TCP.o obj/TCPPerformanceTest.o obj/Telnet.o obj/TFTPc.o obj/Tick.o obj/timer.o obj/UART.o obj/UART2TCPBridge.o obj/UDP.o obj/BerkeleyTCPServerDemo.o obj/linearkeypad.o obj/MainDemo.o
	$(LD) /p18F67J60 /l"C:\Program Files\Microchip\mplabc18\v3.46\lib" "obj\Announce.o" "obj\ARP.o" "obj\AutoIP.o" "obj\BerkeleyAPI.o" "obj\Delay.o" "obj\DHCP.o" "obj\DHCPs.o" "obj\DNS.o" "obj\DNSs.o" "obj\DynDNS.o" "obj\ETH97J60.o" "obj\FTP.o" "obj\Hashes.o" "obj\Helpers.o" "obj\HTTP2.o" "obj\ICMP.o" "obj\IP.o" "obj\LCDBlocking.o" "obj\MPFS2.o" "obj\NBNS.o" "obj\SMTP.o" "obj\SNMP.o" "obj\SNMPv3.o" "obj\SNMPv3USM.o" "obj\SNTP.o" "obj\SPIEEPROM.o" "obj\SPIFlash.o" "obj\SPIRAM.o" "obj\SSL.o" "obj\StackTsk.o" "obj\TCP.o" "obj\TCPPerformanceTest.o" "obj\Telnet.o" "obj\TFTPc.o" "obj\Tick.o" "obj\timer.o" "obj\UART.o" "obj\UART2TCPBridge.o" "obj\UDP.o" "obj\BerkeleyTCPServerDemo.o" "obj\linearkeypad.o" "obj\MainDemo.o" /u_CRUNTIME /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /m"output\OR_SYSTEM_FIRMWARE.map" /w /o"output\OR_SYSTEM_FIRMWARE.cof"

obj/Announce.o : TCPIP/source/Announce.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\Announce.c" -fo="obj\Announce.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/ARP.o : TCPIP/source/ARP.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h TCPIP/TCPIP\ Stack/Helpers.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/delays.h TCPIP/TCPIP\ Stack/Tick.h TCPIP/TCPIP\ Stack/MAC.h TCPIP/TCPIP\ Stack/IP.h TCPIP/TCPIP\ Stack/ARP.h TCPIP/TCPIP\ Stack/UDP.h TCPIP/TCPIP\ Stack/TCP.h TCPIP/TCPIP\ Stack/BerkeleyAPI.h TCPIP/TCPIP\ Stack/UART.h TCPIP/TCPIP\ Stack/ICMP.h TCPIP/source/ARP.c TCPIP/TCPIP\ Stack/TCPIP.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/StackTsk.h TCPIP/TCPIP\ Stack/Delay.h TCPIP/TCPIP\ Stack/ETH97J60.h TCPIP/TCPIP\ Stack/XEEPROM.h TCPIP/TCPIP\ Stack/SPIFlash.h TCPIP/TCPIP\ Stack/SPIRAM.h TCPIP/TCPIP\ Stack/UART2TCPBridge.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\ARP.c" -fo="obj\ARP.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/AutoIP.o : TCPIP/source/AutoIP.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\AutoIP.c" -fo="obj\AutoIP.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/BerkeleyAPI.o : TCPIP/source/BerkeleyAPI.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIP\ Stack/Helpers.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/delays.h TCPIP/TCPIP\ Stack/Tick.h TCPIP/TCPIP\ Stack/MAC.h TCPIP/TCPIP\ Stack/IP.h TCPIP/TCPIP\ Stack/ARP.h TCPIP/TCPIP\ Stack/UDP.h TCPIP/TCPIP\ Stack/TCP.h TCPIP/TCPIP\ Stack/BerkeleyAPI.h TCPIP/TCPIP\ Stack/UART.h TCPIP/TCPIP\ Stack/ICMP.h TCPIP/source/BerkeleyAPI.c TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h TCPIP/TCPIP\ Stack/TCPIP.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIP\ Stack/StackTsk.h TCPIP/TCPIP\ Stack/Delay.h TCPIP/TCPIP\ Stack/ETH97J60.h TCPIP/TCPIP\ Stack/XEEPROM.h TCPIP/TCPIP\ Stack/SPIFlash.h TCPIP/TCPIP\ Stack/SPIRAM.h TCPIP/TCPIP\ Stack/UART2TCPBridge.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\BerkeleyAPI.c" -fo="obj\BerkeleyAPI.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/Delay.o : TCPIP/source/Delay.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h TCPIP/TCPIP\ Stack/Helpers.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/delays.h TCPIP/TCPIP\ Stack/Tick.h TCPIP/TCPIP\ Stack/MAC.h TCPIP/TCPIP\ Stack/IP.h TCPIP/TCPIP\ Stack/ARP.h TCPIP/TCPIP\ Stack/UDP.h TCPIP/TCPIP\ Stack/TCP.h TCPIP/TCPIP\ Stack/BerkeleyAPI.h TCPIP/TCPIP\ Stack/UART.h TCPIP/TCPIP\ Stack/ICMP.h TCPIP/TCPIP\ Stack/TCPIP.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/StackTsk.h TCPIP/TCPIP\ Stack/Delay.h TCPIP/TCPIP\ Stack/ETH97J60.h TCPIP/TCPIP\ Stack/XEEPROM.h TCPIP/TCPIP\ Stack/SPIFlash.h TCPIP/TCPIP\ Stack/SPIRAM.h TCPIP/TCPIP\ Stack/UART2TCPBridge.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\Delay.c" -fo="obj\Delay.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/DHCP.o : TCPIP/source/DHCP.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\DHCP.c" -fo="obj\DHCP.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/DHCPs.o : TCPIP/source/DHCPs.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\DHCPs.c" -fo="obj\DHCPs.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/DNS.o : TCPIP/source/DNS.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h TCPIP/TCPIP\ Stack/Helpers.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/delays.h TCPIP/TCPIP\ Stack/Tick.h TCPIP/TCPIP\ Stack/MAC.h TCPIP/TCPIP\ Stack/IP.h TCPIP/TCPIP\ Stack/ARP.h TCPIP/TCPIP\ Stack/UDP.h TCPIP/TCPIP\ Stack/TCP.h TCPIP/TCPIP\ Stack/BerkeleyAPI.h TCPIP/TCPIP\ Stack/UART.h TCPIP/TCPIP\ Stack/ICMP.h TCPIP/TCPIP\ Stack/TCPIP.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/StackTsk.h TCPIP/TCPIP\ Stack/Delay.h TCPIP/TCPIP\ Stack/ETH97J60.h TCPIP/TCPIP\ Stack/XEEPROM.h TCPIP/TCPIP\ Stack/SPIFlash.h TCPIP/TCPIP\ Stack/SPIRAM.h TCPIP/TCPIP\ Stack/UART2TCPBridge.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\DNS.c" -fo="obj\DNS.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/DNSs.o : TCPIP/source/DNSs.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\DNSs.c" -fo="obj\DNSs.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/DynDNS.o : TCPIP/source/DynDNS.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\DynDNS.c" -fo="obj\DynDNS.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/ETH97J60.o : TCPIP/source/ETH97J60.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIP\ Stack/Helpers.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/delays.h TCPIP/TCPIP\ Stack/Tick.h TCPIP/TCPIP\ Stack/MAC.h TCPIP/TCPIP\ Stack/IP.h TCPIP/TCPIP\ Stack/ARP.h TCPIP/TCPIP\ Stack/UDP.h TCPIP/TCPIP\ Stack/TCP.h TCPIP/TCPIP\ Stack/BerkeleyAPI.h TCPIP/TCPIP\ Stack/UART.h TCPIP/TCPIP\ Stack/ICMP.h TCPIP/source/ETH97J60.c TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/TCPIP.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/StackTsk.h TCPIP/TCPIP\ Stack/Delay.h TCPIP/TCPIP\ Stack/ETH97J60.h TCPIP/TCPIP\ Stack/XEEPROM.h TCPIP/TCPIP\ Stack/SPIFlash.h TCPIP/TCPIP\ Stack/SPIRAM.h TCPIP/TCPIP\ Stack/UART2TCPBridge.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\ETH97J60.c" -fo="obj\ETH97J60.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/FTP.o : TCPIP/source/FTP.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\FTP.c" -fo="obj\FTP.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/Hashes.o : TCPIP/source/Hashes.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h TCPIP/TCPIP\ Stack/Helpers.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/delays.h TCPIP/TCPIP\ Stack/Tick.h TCPIP/TCPIP\ Stack/MAC.h TCPIP/TCPIP\ Stack/IP.h TCPIP/TCPIP\ Stack/ARP.h TCPIP/TCPIP\ Stack/UDP.h TCPIP/TCPIP\ Stack/TCP.h TCPIP/TCPIP\ Stack/BerkeleyAPI.h TCPIP/TCPIP\ Stack/UART.h TCPIP/TCPIP\ Stack/ICMP.h TCPIP/TCPIP\ Stack/TCPIP.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/StackTsk.h TCPIP/TCPIP\ Stack/Delay.h TCPIP/TCPIP\ Stack/ETH97J60.h TCPIP/TCPIP\ Stack/XEEPROM.h TCPIP/TCPIP\ Stack/SPIFlash.h TCPIP/TCPIP\ Stack/SPIRAM.h TCPIP/TCPIP\ Stack/UART2TCPBridge.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\Hashes.c" -fo="obj\Hashes.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/Helpers.o : TCPIP/source/Helpers.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h TCPIP/TCPIP\ Stack/Helpers.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/delays.h TCPIP/TCPIP\ Stack/Tick.h TCPIP/TCPIP\ Stack/MAC.h TCPIP/TCPIP\ Stack/IP.h TCPIP/TCPIP\ Stack/ARP.h TCPIP/TCPIP\ Stack/UDP.h TCPIP/TCPIP\ Stack/TCP.h TCPIP/TCPIP\ Stack/BerkeleyAPI.h TCPIP/TCPIP\ Stack/UART.h TCPIP/TCPIP\ Stack/ICMP.h TCPIP/source/Helpers.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h TCPIP/TCPIP\ Stack/TCPIP.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/StackTsk.h TCPIP/TCPIP\ Stack/Delay.h TCPIP/TCPIP\ Stack/ETH97J60.h TCPIP/TCPIP\ Stack/XEEPROM.h TCPIP/TCPIP\ Stack/SPIFlash.h TCPIP/TCPIP\ Stack/SPIRAM.h TCPIP/TCPIP\ Stack/UART2TCPBridge.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\Helpers.c" -fo="obj\Helpers.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/HTTP2.o : TCPIP/source/HTTP2.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h TCPIP/TCPIP\ Stack/Helpers.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/delays.h TCPIP/TCPIP\ Stack/Tick.h TCPIP/TCPIP\ Stack/MAC.h TCPIP/TCPIP\ Stack/IP.h TCPIP/TCPIP\ Stack/ARP.h TCPIP/TCPIP\ Stack/UDP.h TCPIP/TCPIP\ Stack/TCP.h TCPIP/TCPIP\ Stack/BerkeleyAPI.h TCPIP/TCPIP\ Stack/UART.h TCPIP/TCPIP\ Stack/ICMP.h TCPIP/TCPIP\ Stack/TCPIP.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/StackTsk.h TCPIP/TCPIP\ Stack/Delay.h TCPIP/TCPIP\ Stack/ETH97J60.h TCPIP/TCPIP\ Stack/XEEPROM.h TCPIP/TCPIP\ Stack/SPIFlash.h TCPIP/TCPIP\ Stack/SPIRAM.h TCPIP/TCPIP\ Stack/UART2TCPBridge.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\HTTP2.c" -fo="obj\HTTP2.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/ICMP.o : TCPIP/source/ICMP.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h TCPIP/TCPIP\ Stack/Helpers.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/delays.h TCPIP/TCPIP\ Stack/Tick.h TCPIP/TCPIP\ Stack/MAC.h TCPIP/TCPIP\ Stack/IP.h TCPIP/TCPIP\ Stack/ARP.h TCPIP/TCPIP\ Stack/UDP.h TCPIP/TCPIP\ Stack/TCP.h TCPIP/TCPIP\ Stack/BerkeleyAPI.h TCPIP/TCPIP\ Stack/UART.h TCPIP/TCPIP\ Stack/ICMP.h TCPIP/source/ICMP.c TCPIP/TCPIP\ Stack/TCPIP.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/StackTsk.h TCPIP/TCPIP\ Stack/Delay.h TCPIP/TCPIP\ Stack/ETH97J60.h TCPIP/TCPIP\ Stack/XEEPROM.h TCPIP/TCPIP\ Stack/SPIFlash.h TCPIP/TCPIP\ Stack/SPIRAM.h TCPIP/TCPIP\ Stack/UART2TCPBridge.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\ICMP.c" -fo="obj\ICMP.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/IP.o : TCPIP/source/IP.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h TCPIP/TCPIP\ Stack/Helpers.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/delays.h TCPIP/TCPIP\ Stack/Tick.h TCPIP/TCPIP\ Stack/MAC.h TCPIP/TCPIP\ Stack/IP.h TCPIP/TCPIP\ Stack/ARP.h TCPIP/TCPIP\ Stack/UDP.h TCPIP/TCPIP\ Stack/TCP.h TCPIP/TCPIP\ Stack/BerkeleyAPI.h TCPIP/TCPIP\ Stack/UART.h TCPIP/TCPIP\ Stack/ICMP.h TCPIP/source/IP.c TCPIP/TCPIP\ Stack/TCPIP.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/StackTsk.h TCPIP/TCPIP\ Stack/Delay.h TCPIP/TCPIP\ Stack/ETH97J60.h TCPIP/TCPIP\ Stack/XEEPROM.h TCPIP/TCPIP\ Stack/SPIFlash.h TCPIP/TCPIP\ Stack/SPIRAM.h TCPIP/TCPIP\ Stack/UART2TCPBridge.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\IP.c" -fo="obj\IP.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/LCDBlocking.o : TCPIP/source/LCDBlocking.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h TCPIP/TCPIP\ Stack/Helpers.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/delays.h TCPIP/TCPIP\ Stack/Tick.h TCPIP/TCPIP\ Stack/MAC.h TCPIP/TCPIP\ Stack/IP.h TCPIP/TCPIP\ Stack/ARP.h TCPIP/TCPIP\ Stack/UDP.h TCPIP/TCPIP\ Stack/TCP.h TCPIP/TCPIP\ Stack/BerkeleyAPI.h TCPIP/TCPIP\ Stack/UART.h TCPIP/TCPIP\ Stack/ICMP.h TCPIP/TCPIP\ Stack/TCPIP.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/StackTsk.h TCPIP/TCPIP\ Stack/Delay.h TCPIP/TCPIP\ Stack/ETH97J60.h TCPIP/TCPIP\ Stack/XEEPROM.h TCPIP/TCPIP\ Stack/SPIFlash.h TCPIP/TCPIP\ Stack/SPIRAM.h TCPIP/TCPIP\ Stack/UART2TCPBridge.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\LCDBlocking.c" -fo="obj\LCDBlocking.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/MPFS2.o : TCPIP/source/MPFS2.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h TCPIP/TCPIP\ Stack/Helpers.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/delays.h TCPIP/TCPIP\ Stack/Tick.h TCPIP/TCPIP\ Stack/MAC.h TCPIP/TCPIP\ Stack/IP.h TCPIP/TCPIP\ Stack/ARP.h TCPIP/TCPIP\ Stack/UDP.h TCPIP/TCPIP\ Stack/TCP.h TCPIP/TCPIP\ Stack/BerkeleyAPI.h TCPIP/TCPIP\ Stack/UART.h TCPIP/TCPIP\ Stack/ICMP.h TCPIP/TCPIP\ Stack/TCPIP.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/StackTsk.h TCPIP/TCPIP\ Stack/Delay.h TCPIP/TCPIP\ Stack/ETH97J60.h TCPIP/TCPIP\ Stack/XEEPROM.h TCPIP/TCPIP\ Stack/SPIFlash.h TCPIP/TCPIP\ Stack/SPIRAM.h TCPIP/TCPIP\ Stack/UART2TCPBridge.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\MPFS2.c" -fo="obj\MPFS2.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/NBNS.o : TCPIP/source/NBNS.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\NBNS.c" -fo="obj\NBNS.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/SMTP.o : TCPIP/source/SMTP.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\SMTP.c" -fo="obj\SMTP.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/SNMP.o : TCPIP/source/SNMP.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\SNMP.c" -fo="obj\SNMP.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/SNMPv3.o : TCPIP/source/SNMPv3.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\SNMPv3.c" -fo="obj\SNMPv3.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/SNMPv3USM.o : TCPIP/source/SNMPv3USM.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\SNMPv3USM.c" -fo="obj\SNMPv3USM.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/SNTP.o : TCPIP/source/SNTP.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\SNTP.c" -fo="obj\SNTP.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/SPIEEPROM.o : TCPIP/source/SPIEEPROM.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\SPIEEPROM.c" -fo="obj\SPIEEPROM.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/SPIFlash.o : TCPIP/source/SPIFlash.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\SPIFlash.c" -fo="obj\SPIFlash.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/SPIRAM.o : TCPIP/source/SPIRAM.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\SPIRAM.c" -fo="obj\SPIRAM.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/SSL.o : TCPIP/source/SSL.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\SSL.c" -fo="obj\SSL.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/StackTsk.o : TCPIP/source/StackTsk.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h TCPIP/TCPIP\ Stack/Helpers.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/delays.h TCPIP/TCPIP\ Stack/Tick.h TCPIP/TCPIP\ Stack/MAC.h TCPIP/TCPIP\ Stack/IP.h TCPIP/TCPIP\ Stack/ARP.h TCPIP/TCPIP\ Stack/UDP.h TCPIP/TCPIP\ Stack/TCP.h TCPIP/TCPIP\ Stack/BerkeleyAPI.h TCPIP/TCPIP\ Stack/UART.h TCPIP/TCPIP\ Stack/ICMP.h TCPIP/source/StackTsk.c TCPIP/TCPIP\ Stack/TCPIP.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/StackTsk.h TCPIP/TCPIP\ Stack/Delay.h TCPIP/TCPIP\ Stack/ETH97J60.h TCPIP/TCPIP\ Stack/XEEPROM.h TCPIP/TCPIP\ Stack/SPIFlash.h TCPIP/TCPIP\ Stack/SPIRAM.h TCPIP/TCPIP\ Stack/UART2TCPBridge.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\StackTsk.c" -fo="obj\StackTsk.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/TCP.o : TCPIP/source/TCP.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/Helpers.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/delays.h TCPIP/TCPIP\ Stack/Tick.h TCPIP/TCPIP\ Stack/MAC.h TCPIP/TCPIP\ Stack/IP.h TCPIP/TCPIP\ Stack/ARP.h TCPIP/TCPIP\ Stack/UDP.h TCPIP/TCPIP\ Stack/TCP.h TCPIP/TCPIP\ Stack/BerkeleyAPI.h TCPIP/TCPIP\ Stack/UART.h TCPIP/TCPIP\ Stack/ICMP.h TCPIP/source/TCP.c TCPIP/TCPIP\ Stack/TCPIP.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIPConfig.h TCPIP/TCPIP\ Stack/StackTsk.h TCPIP/TCPIP\ Stack/Delay.h TCPIP/TCPIP\ Stack/ETH97J60.h TCPIP/TCPIP\ Stack/XEEPROM.h TCPIP/TCPIP\ Stack/SPIFlash.h TCPIP/TCPIP\ Stack/SPIRAM.h TCPIP/TCPIP\ Stack/UART2TCPBridge.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\TCP.c" -fo="obj\TCP.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/TCPPerformanceTest.o : TCPIP/source/TCPPerformanceTest.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\TCPPerformanceTest.c" -fo="obj\TCPPerformanceTest.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/Telnet.o : TCPIP/source/Telnet.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\Telnet.c" -fo="obj\Telnet.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/TFTPc.o : TCPIP/source/TFTPc.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\TFTPc.c" -fo="obj\TFTPc.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/Tick.o : TCPIP/source/Tick.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h TCPIP/TCPIP\ Stack/Helpers.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/delays.h TCPIP/TCPIP\ Stack/Tick.h TCPIP/TCPIP\ Stack/MAC.h TCPIP/TCPIP\ Stack/IP.h TCPIP/TCPIP\ Stack/ARP.h TCPIP/TCPIP\ Stack/UDP.h TCPIP/TCPIP\ Stack/TCP.h TCPIP/TCPIP\ Stack/BerkeleyAPI.h TCPIP/TCPIP\ Stack/UART.h TCPIP/TCPIP\ Stack/ICMP.h TCPIP/source/Tick.c TCPIP/TCPIP\ Stack/TCPIP.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/StackTsk.h TCPIP/TCPIP\ Stack/Delay.h TCPIP/TCPIP\ Stack/ETH97J60.h TCPIP/TCPIP\ Stack/XEEPROM.h TCPIP/TCPIP\ Stack/SPIFlash.h TCPIP/TCPIP\ Stack/SPIRAM.h TCPIP/TCPIP\ Stack/UART2TCPBridge.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\Tick.c" -fo="obj\Tick.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/timer.o : TCPIP/source/timer.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/timer.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\timer.c" -fo="obj\timer.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/UART.o : TCPIP/source/UART.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIP\ Stack/Helpers.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/delays.h TCPIP/TCPIP\ Stack/Tick.h TCPIP/TCPIP\ Stack/MAC.h TCPIP/TCPIP\ Stack/IP.h TCPIP/TCPIP\ Stack/ARP.h TCPIP/TCPIP\ Stack/UDP.h TCPIP/TCPIP\ Stack/TCP.h TCPIP/TCPIP\ Stack/BerkeleyAPI.h TCPIP/TCPIP\ Stack/UART.h TCPIP/TCPIP\ Stack/ICMP.h TCPIP/source/UART.c TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h TCPIP/TCPIP\ Stack/TCPIP.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIP\ Stack/StackTsk.h TCPIP/TCPIP\ Stack/Delay.h TCPIP/TCPIP\ Stack/ETH97J60.h TCPIP/TCPIP\ Stack/XEEPROM.h TCPIP/TCPIP\ Stack/SPIFlash.h TCPIP/TCPIP\ Stack/SPIRAM.h TCPIP/TCPIP\ Stack/UART2TCPBridge.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\UART.c" -fo="obj\UART.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/UART2TCPBridge.o : TCPIP/source/UART2TCPBridge.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIP\ Stack/Helpers.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/delays.h TCPIP/TCPIP\ Stack/Tick.h TCPIP/TCPIP\ Stack/MAC.h TCPIP/TCPIP\ Stack/IP.h TCPIP/TCPIP\ Stack/ARP.h TCPIP/TCPIP\ Stack/UDP.h TCPIP/TCPIP\ Stack/TCP.h TCPIP/TCPIP\ Stack/BerkeleyAPI.h TCPIP/TCPIP\ Stack/UART.h TCPIP/TCPIP\ Stack/ICMP.h TCPIP/source/UART2TCPBridge.c TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIP\ Stack/TCPIP.h TCPIP/TCPIP\ Stack/StackTsk.h TCPIP/TCPIP\ Stack/Delay.h TCPIP/TCPIP\ Stack/ETH97J60.h TCPIP/TCPIP\ Stack/XEEPROM.h TCPIP/TCPIP\ Stack/SPIFlash.h TCPIP/TCPIP\ Stack/SPIRAM.h TCPIP/TCPIP\ Stack/UART2TCPBridge.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\UART2TCPBridge.c" -fo="obj\UART2TCPBridge.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/UDP.o : TCPIP/source/UDP.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h TCPIP/TCPIP\ Stack/Helpers.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/delays.h TCPIP/TCPIP\ Stack/Tick.h TCPIP/TCPIP\ Stack/MAC.h TCPIP/TCPIP\ Stack/IP.h TCPIP/TCPIP\ Stack/ARP.h TCPIP/TCPIP\ Stack/UDP.h TCPIP/TCPIP\ Stack/TCP.h TCPIP/TCPIP\ Stack/BerkeleyAPI.h TCPIP/TCPIP\ Stack/UART.h TCPIP/TCPIP\ Stack/ICMP.h TCPIP/source/UDP.c TCPIP/TCPIP\ Stack/TCPIP.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/StackTsk.h TCPIP/TCPIP\ Stack/Delay.h TCPIP/TCPIP\ Stack/ETH97J60.h TCPIP/TCPIP\ Stack/XEEPROM.h TCPIP/TCPIP\ Stack/SPIFlash.h TCPIP/TCPIP\ Stack/SPIRAM.h TCPIP/TCPIP\ Stack/UART2TCPBridge.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\source\UDP.c" -fo="obj\UDP.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/BerkeleyTCPServerDemo.o : TCPIP/BerkeleyTCPServerDemo.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h TCPIP/TCPIP\ Stack/Helpers.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/delays.h TCPIP/TCPIP\ Stack/Tick.h TCPIP/TCPIP\ Stack/MAC.h TCPIP/TCPIP\ Stack/IP.h TCPIP/TCPIP\ Stack/ARP.h TCPIP/TCPIP\ Stack/UDP.h TCPIP/TCPIP\ Stack/TCP.h TCPIP/TCPIP\ Stack/BerkeleyAPI.h TCPIP/TCPIP\ Stack/UART.h TCPIP/TCPIP\ Stack/ICMP.h TCPIP/linearkeypad.h TCPIP/BerkeleyTCPServerDemo.c TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h TCPIP/TCPIP\ Stack/TCPIP.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIP\ Stack/StackTsk.h TCPIP/TCPIP\ Stack/Delay.h TCPIP/TCPIP\ Stack/ETH97J60.h TCPIP/TCPIP\ Stack/XEEPROM.h TCPIP/TCPIP\ Stack/SPIFlash.h TCPIP/TCPIP\ Stack/SPIRAM.h TCPIP/TCPIP\ Stack/UART2TCPBridge.h TCPIP/typedefs.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\BerkeleyTCPServerDemo.c" -fo="obj\BerkeleyTCPServerDemo.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/linearkeypad.o : TCPIP/linearkeypad.c TCPIP/linearkeypad.h TCPIP/linearkeypad.c TCPIP/typedefs.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\linearkeypad.c" -fo="obj\linearkeypad.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

obj/MainDemo.o : TCPIP/MainDemo.c C:/Program\ Files/Microchip/mplabc18/v3.46/h/string.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdio.h TCPIP/TCPIP\ Stack/Helpers.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/delays.h TCPIP/TCPIP\ Stack/Tick.h TCPIP/TCPIP\ Stack/MAC.h TCPIP/TCPIP\ Stack/IP.h TCPIP/TCPIP\ Stack/ARP.h TCPIP/TCPIP\ Stack/UDP.h TCPIP/TCPIP\ Stack/TCP.h TCPIP/TCPIP\ Stack/BerkeleyAPI.h TCPIP/TCPIP\ Stack/UART.h TCPIP/TCPIP\ Stack/ICMP.h TCPIP/MainDemo.h TCPIP/linearkeypad.h TCPIP/MainDemo.c TCPIP/TCPIP\ Stack/TCPIP.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stddef.h TCPIP/TCPIP\ Stack/GenericTypeDefs.h TCPIP/TCPIP\ Stack/Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/p18f67j60.h C:/Program\ Files/Microchip/mplabc18/v3.46/h/stdarg.h TCPIP/HardwareProfile.h TCPIP/Configs/HWP\ PICDN2_ETH97.h TCPIP/TCPIPConfig.h TCPIP/Configs/TCPIP\ ETH97.h TCPIP/TCPIP\ Stack/StackTsk.h TCPIP/TCPIP\ Stack/Delay.h TCPIP/TCPIP\ Stack/ETH97J60.h TCPIP/TCPIP\ Stack/XEEPROM.h TCPIP/TCPIP\ Stack/SPIFlash.h TCPIP/TCPIP\ Stack/SPIRAM.h TCPIP/TCPIP\ Stack/UART2TCPBridge.h TCPIP/typedefs.h
	$(CC) -p=18F67J60 /i"TCPIP\configs" -I"TCPIP\TCPIP Stack" -I"TCPIP" "TCPIP\MainDemo.c" -fo="obj\MainDemo.o" -D__DEBUG -DCFG_INCLUDE_PICDN2_ETH97 -O-

clean : 
	$(RM) "obj\Announce.o" "obj\ARP.o" "obj\AutoIP.o" "obj\BerkeleyAPI.o" "obj\Delay.o" "obj\DHCP.o" "obj\DHCPs.o" "obj\DNS.o" "obj\DNSs.o" "obj\DynDNS.o" "obj\ETH97J60.o" "obj\FTP.o" "obj\Hashes.o" "obj\Helpers.o" "obj\HTTP2.o" "obj\ICMP.o" "obj\IP.o" "obj\LCDBlocking.o" "obj\MPFS2.o" "obj\NBNS.o" "obj\SMTP.o" "obj\SNMP.o" "obj\SNMPv3.o" "obj\SNMPv3USM.o" "obj\SNTP.o" "obj\SPIEEPROM.o" "obj\SPIFlash.o" "obj\SPIRAM.o" "obj\SSL.o" "obj\StackTsk.o" "obj\TCP.o" "obj\TCPPerformanceTest.o" "obj\Telnet.o" "obj\TFTPc.o" "obj\Tick.o" "obj\timer.o" "obj\UART.o" "obj\UART2TCPBridge.o" "obj\UDP.o" "obj\BerkeleyTCPServerDemo.o" "obj\linearkeypad.o" "obj\MainDemo.o" "output\OR_SYSTEM_FIRMWARE.cof" "output\OR_SYSTEM_FIRMWARE.hex" "output\OR_SYSTEM_FIRMWARE.map"

